### ISSUE TITLE
KerbrosComm::S4U2proxy incomplete

### ISSUE THREAD

**Issue by krizex** [skelsec/minikerberos#11]
This function is expected to return the TGS ticket as S4U2Self did, but unfortunately it did not.

**Comment by skelsec** [comment]
It is still a work in progress.

**Comment by skelsec** [comment]
I have updated the code, it should work now.

**Comment by krizex** [comment]
Thanks! I will give a try after setting up my environment.

skelsec <notifications@github.com> 于2020年1月22日周三 上午6:41写道：

**Comment by skelsec** [comment]
Closing this, as no reply was given

**Comment by krizex** [comment]
Hi @skelsec sorry for the late response.
I have successful verified the S4U2Proxy implementation to get a TGS to access another service in my domain.
Great job, thanks!

**Comment by krizex** [comment]
Hi @skelsec Can you port this implementation to the aioclient as the implementation is incomplete also?
