### ISSUE TITLE
AIOKerberosClient::S4U2Proxy incomplete

### ISSUE THREAD

**Issue by krizex** [skelsec/minikerberos#17]
I have verified the implementation of KerbrosClient::S4U2Proxy in #11 .
Please also update the implementation in the AIOKerberosClient.

Thanks!

**Comment by skelsec** [comment]
I have updated the code to support it. Please let me know if it works for you. Sorry for the delay

**Comment by krizex** [comment]
Yes, I have seen that in the latest release. I will verify it later. Thank you!

**Comment by skelsec** [comment]
I consider this verified
