### ISSUE TITLE
ModuleNotFoundError: no module named 'minikerberos.crypto'

### ISSUE THREAD

**Issue by nlinley** [skelsec/minikerberos#23]
I ran into an error with a using msldap that referenced this module.  It was failing to load modules in minikerberos.crypto.hashing.  I noticed that the whole minikerberos.crypto folder is no longer present in the latest version

**Comment by skelsec** [comment]
Hello, the new version of minikerberos using the `unicrypto` library, so all references have been updated to it and the `minikerberos.crypto` library has been removed.  
In case you are encountering issues please provide the full error message and the version you are using, potentially referencing the line in the codebase which is still using the old crypto lib (I couldn't find it)

**Comment by daddycocoaman** [comment]
They were probably referencing this in `msldap`, similar to the `aiosmb` issue.

https://github.com/skelsec/msldap/blob/ed3134135ddf9e13c74a4d7208ef3e48ec898192/msldap/authentication/kerberos/gssapi.py#L9

**Comment by skelsec** [comment]
this issue is now all over the place. Ldap and aiosmb has been resolved now by publishing the most recent code from Porchetta

**Comment by skelsec** [comment]
I can't find the issue in minikerberos, there are no results for that reference.

**Comment by nlinley** [comment]
I ran into the error with msldap's msldap.authentication.kerberos.gssapi file.  I see that its updated in that project's code in github, but on the pip downloaded module v0.3.30, it still references minikerberos.crypto

**Comment by skelsec** [comment]
this is super strange, when I wrote the previous message I also uploaded version 0.3.38 on pip. Can you please try to upgrade again?

**Comment by nlinley** [comment]
I upgrade to 0.3.38 msldap with minikerberos 0.2.20 and its working good now

**Comment by skelsec** [comment]
awesome, closing this issue now!
thx all!

**Comment by skelsec** [comment]
hello, may I ask what OS are you using?
Your `msldap` library is seriously outdated
