### ISSUE TITLE
0.3.0 release has KerberosTarget and KerberosClientSocket incompatibilities

### ISSUE THREAD

**Issue by kulinacs** [skelsec/minikerberos#26]
The 0.3.0 release switched KerberosTarget to use "UniProto.CLIENT_TCP" as the protocol, which is not an expected value in KerberosClientSocket. With this change, create_soc fails with "Unknown socket type".

**Comment by skelsec** [comment]
Ahh sh*t, I forgot to update the blocking IO part. Currently I'm working on adding new features to the lib, I'll add the fix for the blocking part soon. 
In the meantime use the previous version.

**Comment by skelsec** [comment]
New version published, fixes this issue. Please confirm when you have time

**Comment by kulinacs** [comment]
Confirmed it fixed in 0.3.1!
