### ISSUE TITLE
[chore] git tags

### ISSUE THREAD

**Issue by noraj** [skelsec/minikerberos#27]
0.3.0 and 0.3.1 are published on pypi (https://pypi.org/project/minikerberos/#history) but the git tags (https://github.com/skelsec/minikerberos/tags) and github release (https://github.com/skelsec/minikerberos/releases) are missing

**Comment by skelsec** [comment]
0.3.1 has been tagged now. I don't think it would be beneficial to create a tag for 0.3.0
