### ISSUE TITLE
cve202233679 with ccache not work

### ISSUE THREAD

**Issue by enj5oy** [skelsec/minikerberos#33]
I got TGT for user with DO NOT REQUIRE PRE AUTH.
When i pass kirbi ticket  to rubeus all work.
When i convert this ticket to ccache and then use this ticket, i get error
![2023-10-14_16-40](https://github.com/skelsec/minikerberos/assets/143943083/50bf4dd5-5c1a-437c-9d3a-b1265896f7fe)
![2023-10-14_16-41](https://github.com/skelsec/minikerberos/assets/143943083/c75477e7-4d91-4877-ba5d-dfcdfcc924d9)

**Comment by skelsec** [comment]
As far as I know Impacket does not support the kerberos key type of RC4_MD4, which is needed for this ticket to be used.

**Comment by enj5oy** [comment]
@skelsec any recommendations for use ticket from linux?

**Comment by skelsec** [comment]
Wow this issue missed my eye, sorry.
Yes, you can use my `aiosmb` package to perform authentication with the resulting ticket on linux.

**Comment by enj5oy** [comment]
Solve
